FROM ubuntu:14.04
MAINTAINER Carlos I. Pérez Sechi <secci.jr@gmail.com>

RUN sudo apt-get update && sudo apt-get install -y wget

EXPOSE 22
EXPOSE 25
EXPOSE 456
EXPOSE 587
EXPOSE 110
EXPOSE 143
EXPOSE 993
EXPOSE 995
EXPOSE 80
EXPOSE 443
EXPOSE 8080
EXPOSE 8443
EXPOSE 7071

RUN mkdir /tmp/zcs
ADD start.first.sh /tmp/zcs/start.first.sh

CMD ["/bin/bash", "/tmp/zcs/start.first.sh", "-bash"]
